#!/usr/bin/env bash

# need administrator mode before running this, as it relies on CMD, and
# CMD's mklink does not respect the create symbolic link privilege

: '
mklink - Create NTFS (Windows) link that is usable by Windows and Cygwin

Usage: mklink [/D | /H | /J] <link-path> <target-path>

Options:
    /D    Directory Symbolic Link
    /H    Hardlink
    /J    Directory Junction (you should prefer /D)

With no options, it creates a NTFS file symlink.

Also see `winln` in `cygutils-extra` package.
'

if [ "$#" -ge "3" ]; then
    cmd /c mklink "$1" "$(cygpath --windows --absolute "$2")" "$(cygpath --windows "$3")"
else
    cmd /c mklink "$(cygpath --windows --absolute "$1")" "$(cygpath --windows "$2")"
fi
