#!/usr/bin/env sh

executable="$(command which --all "$(basename "$0")" | grep --max-count=1 --invert-match "$(realpath --no-symlinks "$0")")"

if [ -t 0 -a -t 1 ]; then

    exec winpty "$(realpath "$executable")" "$@"

else

    exec "$(realpath "$executable")" "$@"

fi

